name: face_rhythm
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - numpy
    - jupyterlab
    - tensorly
    - opencv-python
    - imageio
    - matplotlib
    - scikit-learn
    - scikit-image
    - librosa
    - pyyaml
    - imageio-ffmpeg
    - tqdm
    - h5py
    - pynwb
    - ipywidgets
    - pytest
    - Pillow
    - opt_einsum    
    - decord
    - torch==1.12.0
    - torchvision==0.13.0
    - torchaudio==0.12.0 
    - --extra-index-url https://download.pytorch.org/whl/cpu
