dir_vid: /Users/akshay/Documents/Harvard/face-rhythm/data
fileName_vid: raw/gmou06_082720_faceTrack_session1.avi
fileName_vid_numDigitsInIteration: 4
fileName_vid_prefix: cam3_2020-11-02-185732-
fileName_vid_suffix: .avi
frameToSet: 2
multiple_files_pref: false
numFrames_allFiles: 109550
numFrames_total_rough: 109550
numVids: 1
path_base_dir: /Users/akshay/Documents/Harvard/face-rhythm/notebooks
path_config: /Users/akshay/Documents/Harvard/face-rhythm/notebooks/config.yaml
path_pts_all: /Users/akshay/Documents/Harvard/face-rhythm/data/processed/pts_all.npy
path_vid_allFiles: [/Users/akshay/Documents/Harvard/face-rhythm/data/raw/gmou06_082720_faceTrack_session1.avi]
print_fileNames_pref: 1
save_dir: /Users/akshay/Documents/Harvard/face-rhythm/data/processed
slash_type: /
vidToSet: 1
vid_Fs: 30.0
vid_height: 480
vid_width: 640
