cdr_dot_size: 1
cdr_frameNum: 0
cdr_num_components: 2
cdr_num_dots: 12824
cdr_spacing: 8
cdr_vidNum: 0
cdr_width_cosKernel: 40
dir_vid: /n/groups/datta/akshay/face-rhythm/data
dot_size: 1
fileName_vid: raw/gmou06_082720_faceTrack_session1.avi
fileName_vid_numDigitsInIteration: 4
fileName_vid_prefix: cam3_2020-11-02-185732-
fileName_vid_suffix: .avi
fps_counterPeriod: 10
frameToSet: 2
framesHalted_afterOutlier: 10
framesHalted_beforeOutlier: 30
lk_criteria: [3, 100, 0.001]
lk_maxLevel: 4
lk_winSize: [35, 35]
multiple_files_pref: false
numFrames_allFiles: 109550
numFrames_total: 109549
numFrames_total_rough: 109550
numVids: 1
optic_multithread: false
outlier_threshold_displacements: 6
outlier_threshold_positions: 40
path_base_dir: /n/groups/datta/akshay/face-rhythm/notebooks
path_config: /n/groups/datta/akshay/face-rhythm/notebooks/config.yaml
path_cosKernel: /n/groups/datta/akshay/face-rhythm/data/processed/cosKernel.npy
path_displacements: /n/groups/datta/akshay/face-rhythm/data/processed/displacements.npy
path_pointInds_toUse: /n/groups/datta/akshay/face-rhythm/data/processed/pointInds_toUse.npy
path_positions: /n/groups/datta/akshay/face-rhythm/data/processed/positions.npy
path_positions_absolute: /n/groups/datta/akshay/face-rhythm/data/processed/positions_absolute.npy
path_pts_all: /n/groups/datta/akshay/face-rhythm/data/processed/pts_all.npy
path_pts_spaced_convDR: /n/groups/datta/akshay/face-rhythm/data/processed/pts_spaced_convDR.npy
path_vid_allFiles: [/n/groups/datta/akshay/face-rhythm/data/raw/gmou06_082720_faceTrack_session1.avi]
printFPS_pref: false
print_fileNames_pref: 1
save_dir: /n/groups/datta/akshay/face-rhythm/data/processed
showVideo_pref: false
slash_type: /
spacing: 3
vidNums_toUse: [0]
vidToSet: 1
vid_Fs: 30.0
vid_height: 480
vid_width: 640
