language: python
# command to install dependencies
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipython
  - pytest
install:
  - pip install -e .
# command to run tests
script:
  - pytest
